# Generated by Django 3.2.4 on 2021-06-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_alter_sales_packaging_options'),
        ('users', '0010_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='product',
            field=models.ManyToManyField(blank=True, to='Product.Product'),
        ),
    ]
