# Generated by Django 3.2.4 on 2021-06-09 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210609_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technician',
            old_name='clinic',
            new_name='pharmacy',
        ),
    ]
