# Generated by Django 3.2.4 on 2021-06-09 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_clinic_technician_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.clinicgroup'),
        ),
    ]
