# Generated by Django 3.2.4 on 2021-06-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='GST',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
