# Generated by Django 3.2.4 on 2021-06-04 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
        ('Product', '0004_auto_20210605_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_packaging',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='list.form'),
        ),
        migrations.AlterField(
            model_name='product',
            name='GST',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
