# Generated by Django 3.2.4 on 2021-06-04 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('Product', '0005_auto_20210605_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_packaging',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.packaging'),
        ),
    ]
