# Generated by Django 3.2.4 on 2021-06-05 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_auto_20210605_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='packaging',
        ),
        migrations.AddField(
            model_name='sales_packaging',
            name='linked_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.product'),
        ),
    ]
