# Generated by Django 3.2.4 on 2021-06-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_auto_20210605_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_packaging',
            name='linked_product',
        ),
        migrations.RemoveField(
            model_name='sales_packaging',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sales_packaging',
            name='tax',
        ),
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.ManyToManyField(blank=True, to='Product.Sales_Packaging'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
