# Generated by Django 3.2.4 on 2021-06-05 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_target_species'),
        ('Product', '0010_auto_20210605_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='targe_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='list.target_species'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='Compounded Product', max_length=200, null=True),
        ),
    ]
