# Generated by Django 3.2.4 on 2021-06-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_auto_20210605_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
