# Generated by Django 3.2.4 on 2021-06-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_product_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='targe_species',
            new_name='target_species',
        ),
        migrations.AddField(
            model_name='product',
            name='compound',
            field=models.BooleanField(default=True),
        ),
    ]
