# Generated by Django 3.2.4 on 2021-06-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_auto_20210605_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_line',
            options={'ordering': ['linked_product']},
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
