# Generated by Django 3.2.4 on 2021-06-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_auto_20210605_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='compound',
        ),
    ]
