# Generated by Django 3.2.4 on 2021-06-06 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_product_formula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales_packaging',
            options={'ordering': ('short_desc',), 'verbose_name': 'Packaging', 'verbose_name_plural': 'Packaging'},
        ),
    ]
