# Generated by Django 3.2.4 on 2021-06-04 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_desc', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Excipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_descr', models.CharField(blank=True, max_length=256, null=True)),
                ('drug_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='list.form')),
            ],
        ),
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_descr', models.CharField(blank=True, max_length=256, null=True)),
                ('drug_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='list.form')),
            ],
        ),
    ]
