# Generated by Django 3.2.4 on 2021-06-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210606_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excipient',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
