# Generated by Django 3.2.4 on 2021-06-06 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_target_species'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target_species',
            options={'ordering': ('name',), 'verbose_name': 'Target species', 'verbose_name_plural': 'Target species'},
        ),
    ]
