# Generated by Django 3.2.4 on 2021-06-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compound',
            options={'ordering': ('name',), 'verbose_name': 'Batch Record', 'verbose_name_plural': 'Batch Records'},
        ),
    ]
