# Generated by Django 3.2.4 on 2021-06-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_rename_max_qty_compound_qty_to_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='batch_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
