# Generated by Django 3.2.4 on 2021-06-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_auto_20210606_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
