# Generated by Django 3.2.4 on 2021-06-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0006_alter_compound_line_linked_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compound_line',
            old_name='Amount',
            new_name='amount_to_weigh',
        ),
    ]
