# Generated by Django 3.2.4 on 2021-06-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0007_rename_amount_compound_line_amount_to_weigh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound_line',
            name='name',
        ),
    ]
