# Generated by Django 3.2.4 on 2021-06-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0008_remove_compound_line_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='qty_to_make',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
