# Generated by Django 3.2.4 on 2021-06-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0009_alter_compound_qty_to_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound_line',
            name='weighed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
