# Generated by Django 3.2.4 on 2021-06-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0015_instruction_instruction_form'),
        ('manufacturing', '0011_compound_instruction_step_compounding_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compounding_instruction',
            name='Instruction_form',
        ),
        migrations.RemoveField(
            model_name='compounding_instruction',
            name='linked_product',
        ),
        migrations.AddField(
            model_name='compound',
            name='instruction',
            field=models.ManyToManyField(blank=True, to='formulary.Instruction'),
        ),
        migrations.DeleteModel(
            name='Compound_Instruction_Step',
        ),
        migrations.DeleteModel(
            name='Compounding_Instruction',
        ),
    ]
