# Generated by Django 3.2.4 on 2021-06-10 02:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0015_instruction_instruction_form'),
        ('manufacturing', '0013_auto_20210610_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction_Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.IntegerField(blank=True, default=0, null=True)),
                ('ix', ckeditor.fields.RichTextField(default=True, verbose_name='Instruction')),
                ('linked_instruction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Compound_Instruction', to='formulary.instruction')),
            ],
            options={
                'verbose_name': 'Instruction Step',
                'verbose_name_plural': 'Instruction Step',
                'ordering': ['step_no'],
            },
        ),
    ]
