# Generated by Django 3.2.4 on 2021-06-10 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0015_instruction_instruction_form'),
        ('manufacturing', '0014_instruction_step'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instruction_Step',
            new_name='Compounding_Instruction_Step',
        ),
    ]
