# Generated by Django 3.2.4 on 2021-06-11 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0016_alter_compounding_instruction_step_linked_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound_instruction',
            name='linked_product',
        ),
        migrations.AddField(
            model_name='compound_line',
            name='name',
            field=models.CharField(blank=True, db_index=True, default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='compounding_instruction_step',
            name='linked_instruction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Compound_Instruction_Step_to_Compound_Instruction', to='manufacturing.compound_instruction'),
        ),
    ]
