# Generated by Django 3.2.4 on 2021-06-06 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('list', '0002_target_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='list.form')),
            ],
        ),
    ]
