# Generated by Django 3.2.4 on 2021-06-06 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_packaging_options'),
        ('formulary', '0002_auto_20210606_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula_line',
            name='active',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.excipient'),
        ),
    ]
