# Generated by Django 3.2.4 on 2021-06-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0003_alter_formula_line_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formula_line',
            options={'ordering': ['name'], 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AddField(
            model_name='formula',
            name='max_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
