# Generated by Django 3.2.4 on 2021-06-06 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0004_auto_20210606_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formula_line',
            old_name='strength',
            new_name='Amount',
        ),
    ]
