# Generated by Django 3.2.4 on 2021-06-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0006_auto_20210606_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formula',
            options={'ordering': ('name',), 'verbose_name': 'Master Manufacturing Record', 'verbose_name_plural': 'Master Manufacturing Records'},
        ),
    ]
