# Generated by Django 3.2.4 on 2021-06-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0008_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='Ix',
            field=models.CharField(blank=True, db_index=True, default=True, max_length=2000, verbose_name='Instruction'),
        ),
    ]
