# Generated by Django 3.2.4 on 2021-06-09 09:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0009_alter_instruction_ix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='Ix',
        ),
        migrations.AddField(
            model_name='instruction',
            name='ix',
            field=ckeditor.fields.RichTextField(blank=True, db_index=True, default=True, max_length=2000, verbose_name='Instruction'),
        ),
    ]
