# Generated by Django 3.2.4 on 2021-06-09 09:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0011_alter_instruction_ix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='ix',
            field=ckeditor.fields.RichTextField(default=True, verbose_name='Instruction'),
        ),
    ]
