# Generated by Django 3.2.4 on 2021-06-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0013_auto_20210609_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='linked_product',
        ),
        migrations.AddField(
            model_name='formula',
            name='Instruction',
            field=models.ManyToManyField(blank=True, to='formulary.Instruction'),
        ),
    ]
