# Generated by Django 3.2.4 on 2021-06-09 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_alter_target_species_options'),
        ('formulary', '0014_auto_20210609_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='Instruction_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='list.form'),
        ),
    ]
