# Generated by Django 3.2.4 on 2021-06-10 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0015_instruction_instruction_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='Instruction',
        ),
        migrations.AddField(
            model_name='instruction',
            name='linked_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.formula'),
        ),
    ]
