# Generated by Django 3.2.4 on 2021-06-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0017_alter_instruction_step_step_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction_step',
            name='step_no',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='sub-step'),
        ),
    ]
