# Generated by Django 3.2.4 on 2021-06-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0019_auto_20210611_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formula',
            options={'ordering': ('name',), 'verbose_name': 'Master Formula', 'verbose_name_plural': 'Master Formulas'},
        ),
        migrations.AddField(
            model_name='formula',
            name='available',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
