# Generated by Django 3.2.4 on 2021-06-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0020_auto_20210612_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='available',
        ),
        migrations.AddField(
            model_name='formula',
            name='in_process',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Intermediate Step'),
        ),
    ]
