# Generated by Django 3.2.4 on 2021-06-08 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customer_user'),
        ('orders', '0006_auto_20210608_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.clinic'),
        ),
    ]
