# Generated by Django 3.2.4 on 2021-06-08 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_pharmacy'),
        ('orders', '0007_alter_client_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
