# Generated by Django 3.2.4 on 2021-06-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_client_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client',
            new_name='clinic',
        ),
    ]
