# Generated by Django 3.2.4 on 2021-06-09 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210609_1206'),
        ('orders', '0016_orderitem_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='pet',
            field=models.ForeignKey(blank=True, default='Emergency Use', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.pet'),
        ),
    ]
