# Generated by Django 3.2.4 on 2021-06-12 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20210612_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping_address',
        ),
    ]
