# Generated by Django 3.2.4 on 2021-06-12 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210609_1206'),
        ('Product', '0017_alter_sales_packaging_options'),
        ('orders', '0021_remove_orderitem_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='doctor',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.practitioner'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='packaging',
            field=models.OneToOneField(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.sales_packaging'),
        ),
    ]
