# Generated by Django 3.2.4 on 2021-06-12 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_alter_sales_packaging_options'),
        ('orders', '0022_auto_20210612_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='packaging',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.sales_packaging'),
        ),
    ]
