# Generated by Django 3.2.4 on 2021-06-13 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_customer_user'),
        ('Product', '0017_alter_sales_packaging_options'),
        ('orders', '0023_alter_orderitem_packaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.practitioner'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='packaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.sales_packaging'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.pet'),
        ),
    ]
