# Generated by Django 3.2.4 on 2021-06-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='rx_written',
            field=models.DateField(blank=True, null=True),
        ),
    ]
