# Generated by Django 3.2.4 on 2021-07-10 23:19

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_category_image'),
        ('orders', '0034_auto_20210711_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='packaging',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='product', chained_model_field='packaging', null=True, to='Product.Product', verbose_name='sale packaging'),
        ),
    ]
