# Generated by Django 3.2.4 on 2021-07-10 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_packaging_options'),
        ('orders', '0035_alter_orderitem_packaging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='packaging',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='packaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.packaging'),
        ),
    ]
