# Generated by Django 3.2.4 on 2021-07-10 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_category_image'),
        ('orders', '0036_auto_20210711_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='packaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.sales_packaging'),
        ),
    ]
